<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework Condition="'$(CoreTargetFramework)' != ''">$(CoreTargetFramework)</TargetFramework>
		<TargetFramework Condition="'$(CoreTargetFramework)' == ''">net8.0</TargetFramework>
		<TargetFramework Condition="'$(CoreTargetFramework)' != ''">$(CoreTargetFramework)</TargetFramework>
		<TargetFramework Condition="'$(CoreTargetFramework)' == ''">net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Webefinity.Cadence.UI" Version="0.0.1-beta02" />
	  <PackageReference Include="Webefinity.Cadence.Upload" Version="0.0.1-beta01" />
	</ItemGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Webefinity.ContentRoot.IndexUI\Webefinity.ContentRoot.IndexUI.csproj" />
		<ProjectReference Include="..\Webefinity.Module.Blocks.Abstractions\Webefinity.Module.Blocks.Abstractions.csproj" />
		<ProjectReference Include="..\Webefinity.Module.Blocks.Data\Webefinity.Module.Blocks.Data.csproj" />
		<ProjectReference Include="..\Webefinity.Module.SiteMap.Abstractions\Webefinity.Module.SiteMap.Abstractions.csproj" />
		<ProjectReference Include="..\Webefinity.Validation.Components\Webefinity.Validation.Components.csproj" />
	</ItemGroup>

</Project>
