<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>$(CoreTargetFramework)</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    		<ProjectReference Include="..\Webefinity.Module.Guides.Abstractions\Webefinity.Module.Guides.Abstractions.csproj" />
    		<ProjectReference Include="..\Webefinity.Module.Frontmatter\Webefinity.Module.Frontmatter.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Webefinity.Cadence.UI" Version="0.0.1-beta02" />
  </ItemGroup>

</Project>
