// <auto-generated />
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orleans.NpgsqlTenancy;

#nullable disable

namespace Orleans.NpgsqlTenancy.Migrations
{
    [DbContext(typeof(StateDbContext))]
    partial class StateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Orleans.NpgsqlTenancy.GrainStateType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("StateName")
                        .HasColumnType("text");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonDocument>("State")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id", "StateName");

                    b.ToTable("States");
                });
#pragma warning restore 612, 618
        }
    }
}
