<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework Condition="'$(CoreTargetFramework)' != ''">$(CoreTargetFramework)</TargetFramework>
		<TargetFramework Condition="'$(CoreTargetFramework)' == ''">net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>


	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
		<PackageReference Include="Webefinity.Cadence.UI" Version="0.0.1-beta02" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Webefinity.ContentRoot.Abstractions\Webefinity.ContentRoot.Abstractions.csproj" />
		<ProjectReference Include="..\Webefinity.ContentRoot.Index.Shared\Webefinity.ContentRoot.Index.Shared.csproj" />
		<ProjectReference Include="..\Webefinity.Results\Webefinity.Results.csproj" />
	</ItemGroup>

</Project>
